language: node_js
node_js:
- '0.11'
before_install:
- npm install -g bower
- bower install | xargs echo
- npm install -g grunt-cli
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
  - grunt build
deploy:
  provider: s3
  access_key_id: AKIAIFM2S4SNNDNCRKIA
  secret_access_key: 
    secure: "QYjnoQhZPd82F8lr4nc2IRjijkSbqgPZ6TFJoLGnJ1Qba+wKMF/8SEgkbyND6/nG+fYbvajvOSpBINRhJyuL4Y3YRVk4zEzaHltOZgmFJvZbV7U7eanjcovzDmDh0rcxdsfpG/iArLiNRGUJluKqHghlrOR7k9Jnwn3IT8KU+7A="
  bucket: test.zorba.io
  skip_cleanup: true
  local-dir: dist
