language: node_js
node_js:
- '0.11'
before_install:
- npm install -g bower
- bower install | xargs echo
- npm install -g grunt-cli
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
  - grunt build
deploy:
  - provider: s3
    access_key_id: AKIAI6QIGHTTACHYG6MA
    secret_access_key:
      secure: Wpff7D4i6ZRRaye6KHxEDmHVwdM2M2vTkWYQsJvtJcEOuLeI6ly6RBwWCxJbB/1MG+sC+FFA9/ZfNBP0FT6+pj3ZPLWzTshwG0b2CK7dD/tbfVqaFuxhrTvl1vQzKGZcX22llwnaGCHaL62eMec0EgRxyTUskfo9Iw6eyfp+H34=
    bucket: zorba.28.io
    skip_cleanup: true
    local-dir: dist
    endpoint: zorba.28.io.s3-website-us-east-1.amazonaws.com
    detect_encoding: true
    on:
      branch: master
      repo: 28msec/www.zorba.io
  - provider: s3
    access_key_id: AKIAI6QIGHTTACHYG6MA
    secret_access_key:
      secure: Wpff7D4i6ZRRaye6KHxEDmHVwdM2M2vTkWYQsJvtJcEOuLeI6ly6RBwWCxJbB/1MG+sC+FFA9/ZfNBP0FT6+pj3ZPLWzTshwG0b2CK7dD/tbfVqaFuxhrTvl1vQzKGZcX22llwnaGCHaL62eMec0EgRxyTUskfo9Iw6eyfp+H34=
    bucket: zorba-site.28.io
    skip_cleanup: true
    local-dir: dist
    endpoint: zorba-site.28.io.s3-website-us-east-1.amazonaws.com
    detect_encoding: true
    on:
      branch: beta
      repo: 28msec/www.zorba.io

